### ISSUE TITLE
UK Boxing Day should be 2020-12-28, not 2020-12-26

### ISSUE THREAD

**Issue by ShaheedHaque** [jaraco/calendra#15]
We just noticed that the UK Boxing Day should be 2020-12-28, not 2020-12-26. I believe this is fixed in upstream, so a resync is likely in order.

**Comment by jaraco** [comment]
I suspect that boxing day isn't handled as expected not because the library is out of sync, but due to the way calendra handles holidays differently. I'll create a separate issue to capture the need to sync. I did start work on a sync, but gave up before I got through the changes.

**Comment by jaraco** [comment]
There are already tests in the current version of calendra to capture boxing day 2020 (https://github.com/jaraco/calendra/blob/8323365c36d0316963be221d01c06d4853c690aa/calendra/tests/test_europe.py#L1018-L1019).

Here's where Calendra shines and Workalendar fails. Workalendar will show two holidays, one on the 26th and another on the 28th. Calendra shows one holiday, occurring on the 26th, but observed on the 28th.

Can you provide more information about what expectation was violated? I suspect there's a different usage that would provide the behavior your expect.

**Comment by ShaheedHaque** [comment]
Oh, it looks like I got myself confused between `self.holidays()` and `self.get_observed_date()`: my bad.
