### ISSUE TITLE
New collaborator and cut release for v7.0.0

### ISSUE THREAD

**Issue by jaraco** [jaraco/calendra#19]
@shaheedhaque, I've invited you as a collaborator on this project. With the integrated CI, and with the changelog up-to-date, all that's needed to cut a release is to tag it (i.e. `git tag -a -m "" v7.0.0`). Would you care to do the honors?

Although you don't need access to PyPI in order to cut releases, I'd also like to grant you maintainer access there as well in case a manual release is needed and to reduce the bus factor on the project. Just let me know your userid there.

**Comment by ShaheedHaque** [comment]
Thanks for the invite. I've just accepted but before I try to cut the
release, did you see my note about the "original" observance shifts? I
thought I'd double check since this is a definite behaviour change w.r.t
previous versions (and Workalendar) and probably needs an entry in
CHANGES.rst?

P.S. And thanks for the kind words... I can only say I learnt from the best!

**Comment by jaraco** [comment]
I have seen the note and I've not had the time to fully absorb the implications. I should probably go back to that PR and double-check the tests. If the tests pass as found on workalendar, then I'm comfortable with it. If the tests had to be changed to pass, then I'd be concerned. It's important that the tests reflect the intention, which can be different for calendra (model the holiday on its declared day and separately model its observed date). I hope to take a look at that at some point, but honestly, I'm okay with the release going out and fixes to land later.

**Comment by ShaheedHaque** [comment]
OK. I propose to add an entry to the change history describing the change and push the release out in the coming days...

**Comment by ShaheedHaque** [comment]
@jaraco OK, I created/pushed the tag, and saw some automation run. I just created user "srhaque" on PyPI.org. Do let me know if I need to do anything else!
