### ISSUE TITLE
Do not apply "floating monday" holidays by default to  western calendars

### ISSUE THREAD

**Issue by sevdog** [jaraco/calendra#29]
Not every country follows the "floating monday" mechanism for holydays. For what I was able to figure out this is mainly used in the USA but not in Europe (certainly not in Italy).

https://github.com/jaraco/calendra/blob/40ec0791697b5de5c749cdb122e8365e64800517/calendra/core.py#L495

The default `observance_shift` should be left `None` or empty dict and should be set only to single calendars.

**Comment by jaraco** [comment]
Released in v7.9.1. Sorry for the delay. In the future, feel free to mention me if you're awaiting too long.
