### ISSUE TITLE
Finnish fixed holidays are moved to the next monday if they occur on the weekend

### ISSUE THREAD

**Issue by mikko-ahlroth-vincit** [jaraco/calendra#4]
I'm using calendra 1.1.3 on Python 2.7.8. I'm using the Finnish holiday calendar and have noticed a problem with it.

When using the Finnish calendar, fixed holidays that occur on a weekend are moved to the next working day. Example, the Finnish Independence Day that is the 6th of December:

```
In [3]: holiday_calendar.is_observed_holiday(date(2014, 12, 8))                                                       
Out[3]: True

In [4]: holiday_calendar.is_observed_holiday(date(2014, 12, 6))                                                       
Out[4]: False

In [7]: holiday_calendar.get_observed_date(date(2014, 12, 6))                                                         
Out[7]: datetime.date(2014, 12, 8)
```

This also happens with the Labour Day (1st of May). But in Finland the day off is not transferred to the next monday if the day occurs on the weekend. I can't find a source on it though, but you can check other calendars such as http://www.timeanddate.com/holidays/finland/.

This issue can be fixed by setting an `observance_shift = dict()` for the Finnish calendar, though I arrived at the value of `dict()` just by random testing (I don't know the format) and I don't know if it has any adverse effects.

**Comment by jaraco** [comment]
Thanks for the feedback. Can you write a test in test_europe to capture this expectation/failure, and maybe model it after the test in test_africa:SouthAfricaTest.test_year_2013?

**Comment by jaraco** [comment]
You're probably right about the fix. Are there no holidays in Finland that are shifted to the following work day for observance?

**Comment by mikko-ahlroth-vincit** [comment]
That's correct, they are not shifted in Finland. I've fetched the latest commit and can confirm it passes my (simple) test cases. Thanks for the fix!
